### PR TITLE
Add support for I2C display on STM32.

### PR DESCRIPTION
**Pull request by ghent360**
tested on SSD1306 oled display using STM32 arduino code from:
https://github.com/stm32duino/Arduino_Core_STM32 on Nucleo F446RE board.

### CODE REVIEW

**Comment by olikraus** [comment]
I do not work any more on u8glib. Instead U8g2 is the newer version, which also includes STM32 support.

**Comment by ghent360** [comment]
I understand. Unfortunately your creation is too good and refuses to die.
Projects like Marlin depend on it and there is little appetite to switch to
the new version.

**Comment by olikraus** [comment]
> Projects like Marlin depend on it and there is little appetite to switch to the new version.

Yes, I know. Marlin stays with U8glib because of the size. But adding new features like UTF-8 or STM32 support requires a little bit more ROM. 
U8g2 has better support for new platforms, but the new internal APIs and abstraction layers made U8g2 a little bit bigger.

**Review by olikraus — COMMENTED** [review]
It doesn't make sense to add this here, because it will be overwriten with any further u8glib release.

**Comment by ghent360** [comment]
Would you kindly point me to the right repo?

**Comment by olikraus** [comment]
It would be this: https://github.com/olikraus/u8glib

However, there is no plan to create another release. Any option to use u8g2 instead?

**Pull request closed without merging**
